# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SAMRAT' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SAMRAT
  pod 'MarqueeLabel'
	pod 'SwiftyJSON'
  pod 'Alamofire','4.9.1'
#	pod 'AlamofireImage'
	pod 'IQKeyboardManager'
	pod 'SwiftValidator', :git => 'https://github.com/jpotts18/SwiftValidator.git', :branch => 'master'
  pod 'SwiftMessages', '~> 5.0'
	pod 'OneSignal'
  pod 'ScalingCarousel'
  pod 'AARatingBar'
  pod 'UIViewUseful'
  pod 'VACalendar'
  pod 'SVProgressHUD'
  pod 'Kingfisher', '~> 4.0'
  pod 'MiniPlayer'
  pod 'MASegmentedControl'
  pod "KRPullLoader"
  pod 'GoogleSignIn'
  pod 'Firebase/Auth'
  pod 'FBSDKLoginKit'
  pod 'SwiftKeychainWrapper'
  pod "KRProgressHUD"
  pod 'WMSegmentControl'
  pod 'UITextView+Placeholder'
  pod 'FSPagerView'
  pod 'FDWaveformView'
  pod 'ZAlertView', '~> 1.0.4' # old 0.3.3
  pod 'Toast-Swift', '~> 5.0.1'
  pod 'goSellSDK'
  pod 'SVPinView', '~> 1.0'
  pod 'iOSDropDown'
  pod 'libPhoneNumber-iOS', '~> 0.8'
  pod 'Firebase/Messaging'
#  pod 'CHXCoverFlowView'

  target 'SAMRATTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SAMRATUITests' do
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
end
